version: '3.5'

services:

  mysql:
    image: mysql:5.7.21
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql_vol/init:/docker-entrypoint-initdb.d
      - ./mysql_vol/conf/:/etc/mysql/conf.d
    networks:
      - integration_tools_net
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  sonarqube:
      image: sonarqube:7.6-community
      container_name: sonarqube
      depends_on:
        - mysql
      volumes:
        - ./sonarqube_vol/conf:/opt/sonarqube/conf
        - ./sonarqube_vol/data:/opt/sonarqube/data
        - ./sonarqube_vol/extensions:/opt/sonarqube/extensions
        - ./sonarqube_vol/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      networks:
        - integration_tools_net
      #command: -Dsonar.web.context=/sonarqube
      ports:
        - '9999:9000'
        - '9092:9092'
      environment:
        - SONAR_JDBC_USERNAME=sonar
        - SONAR_JDBC_PASSWORD=sonar
        - SONAR_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8
      restart: always

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: always
    hostname: 'jenkins'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - './jenkins_vol:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - integration_tools_net

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "8000:80"
      - "8443:8443"
      - "8822:22"
    volumes:
      - ./gitlab_vol/cofig:/etc/gitlab
      - ./gitlab_vol/data:/var/opt/gitlab
      - ./gitlab_vol/logs:/var/log/gitlab
    networks:
      - integration_tools_net

networks:
  integration_tools_net:
    driver: bridge

volumes:
  gitlab_vol:
  sonarqube_vol:
  jenkins_vol:
  mysql_vol:
